services:
  app_builder:
    image: service/app_builder
    build: 
      context: ./server
      dockerfile: ./builder/Dockerfile
    # network_mode: host

  server:
    # container_name: app
    image: service/app_rust
    build: ./server
    # network_mode: host

    networks:
      - host

    ports:
      - "5001-5002:5000"
    depends_on:
      - app_builder
    healthcheck:
      test: ["CMD", "curl", "-i", "http://localhost:5000/teste"]
      retries: 1
      interval: 3s
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
    
  nginx:
    image: nginx:latest
    # container_name: nginx
    # working_dir: /etc/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # network_mode: host
    networks:
      - host

networks:
  host:
    name: host
    external: true